config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :clubs, only: %i[new create show index destroy] do
    resources :memberships, only: %i[new create]
  end
  get "/profile", to: "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :description, presence: true
  validates :genre, presence: true
  validates :published, presence: true, comparison: { less_than: Date.today }
  validates :image, presence: true
  validates :isbn,
            presence: true,
            uniqueness: true,
            format: { with: /\A(97(8|9))?\d{9}-?[\dX]?\z/, message: 'isbn is invalid, must isbn 10 or 13 format' }
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :user
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  validates :name, presence: true, length: { in: 3..15 }
  after_create :add_owner_memberships

  private

  def add_owner_memberships
    Membership.create(user: user, club: self)
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :club
  validates_uniqueness_of :user_id, scope: :club_id, message: "is already a member of this club"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memberships
  has_many :clubs, through: :memberships

  validates :username,
            presence: true,
            length: { in: 3..10 },
            uniqueness: { case_sensitive: false }

  validates :first_name,
            :last_name,
            presence: true,
            format: { with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/,
                      message: 'only allows letters and one space after a letter' },
            length: { maximum: 25 }

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def initials
    first_names = first_name.split(/[\s,-]+/).map { |name| name[0] }.join.upcase
    last_names = last_name.split(/[\s,-]+/).map { |name| name[0] }.join.upcase
    "#{first_names}#{last_names}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_club_access, except: %i[create new index]

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    @club.user = current_user
    if @club.save!
      redirect_to club_path(@club), notice: 'Your club was successfully created.'
    else
      render 'new'
    end
  end

  def show
    @club = Club.find(params[:id])
    @members = @club.memberships
  end

  def index
    @clubs = current_user.clubs
  end

  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    redirect_to clubs_url, notice: 'Club was successfully deleted.'
  end

  private

  def club_params
    params.require(:club).permit(:name)
  end

  def authorize_club_access
    # Verify that the user has a membership to the club
    club = Club.find(params[:id])
    redirect_to root_path, alert: 'You are not a member of this club.' unless current_user.clubs.include?(club)
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_club, only: %i[new create]

  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.new
    @membership.user = User.find_by(email: membership_params[:user])
    @membership.club = @club
    if @membership.save!
      redirect_to club_path(@club), notice: "#{@membership.user.username} was added to the club"
    else
      render :new, status: :unprocessable_entity, notice: 'The user was not added to the club.'
    end
  end

  private

  def set_club
    @club = Club.find(params[:club_id])
  end

  def membership_params
    params.require(:membership).permit(:user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :redirect_to_club_index_if_member, only: [:home]

  def home
  end

  private

  def redirect_to_club_index_if_member
    redirect_to clubs_path if current_user&.clubs&.any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user, only: [:show]

  def show
    @user = current_user
  end

  private

  def authorize_user
    return unless current_user == @user

    flash[:alert] = "Your can only view your profile"
    redirect_to profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clubs/index.html.erb
<div>
  <h1>Your Clubs</h1>
  <div class="cards">
    <% @clubs.each do |club| %>
      <div class="card">
        <h4> <%=link_to club.name, club_path(club) %> </h4>
      </div>
    <% end %>
  </div>
</div>

app/views/clubs/new.html.erb
<div class="container">
  <%= simple_form_for @club do |f| %>
    <%= f.input :name, label: "Club Name", placeholder: 'e.g. friends' %>
    <%= f.submit "Start Your Club" %>
  <% end %>
</div>

app/views/clubs/show.html.erb
<h1><%= @club.name %></h1>
<%= link_to "Add a friend to your club", new_club_membership_path(@club), class: "btn btn-flat" %>
<%= link_to "Delete Club", club_path(@club), data: {turbo_method: :delete, turbo_confirm: "Do you really want to delete this club?"}%>
<div>
  <h2>Club Members</h2>
  <ul>
    <% @members.each do |member| %>
      <li><%= member.user.username %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvShowAndBookClub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/memberships/new.html.erb
<div class="container">
  <h1>Add A Friend To Your Club</h1>
  <%= simple_form_for [@club, @membership] do |f| %>
    <%= f.input :user, label: "User's Email", placeholder: 'email@email.com' %>
    <%= f.submit "Add To Your Club" %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path "https://res.cloudinary.com/dm6g22zui/image/upload/v1671878441/v4hpmsdkpvwjwsocimln.jpg"%>');">
  <div class="container">
    <h1>Create a TV and book club with your <strong> friends</strong> and <strong>get in sync</strong>!</h1>
    <% if user_signed_in? %>
      <%= link_to "Create a club!", new_club_path, class: "btn btn-flat" %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-flat" %>
    <% end %>
  </div>
</div>
<div class="container">
    <h2 class="text-center">How it works</h2>
    <div class="cards">

      <div class="card">
        <h4>Create a Club</h4>
        <p>Invite Your Friends</p>
      </div>

      <div class="card">
        <h4>Nominate a book or TV show</h4>
        <p>Club members can update and view the progress of others</p>
      </div>

      <div class="card">
        <h4>Organise Meetup</h4>
        <p>Set your meetup and get directions</p>
      </div>

    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Your Favourite Club App!
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-all">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= cl_image_tag("mcugmqch41ugrt6txp0g") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <nav class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Club", new_club_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Your Clubs", clubs_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dm6g22zui/image/upload/v1669386147/iftyrovfzfvfv3m9bdrx.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</nav>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>